# Generated by Django 6.0.7 on 2026-08-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_noches', models.IntegerField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_hospedaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios_adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion_servicios', models.TextField(blank=True, null=True)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('otro', 'Otro')], max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
